<a href="https://colab.research.google.com/github/Darksoul913/Pro-C140/blob/main/Pro_C141.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2022.6.15)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json

{'kaggle.json': b'{"username":"siddheshamrutkar","key":"30e01802f50c6ff984bb792686f6aa81"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d gspmoreira/articles-sharing-reading-from-cit-deskdrop

articles-sharing-reading-from-cit-deskdrop.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
!unzip articles-sharing-reading-from-cit-deskdrop.zip

Archive:  articles-sharing-reading-from-cit-deskdrop.zip
replace shared_articles.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: shared_articles.csv
replace users_interactions.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: users_interactions.csv

In [ ]:
!ls

 articles-sharing-reading-from-cit-deskdrop.zip   sample_data
'kaggle (1).json'				  shared_articles.csv
 kaggle.json					  users_interactions.csv

In [ ]:
import pandas as pd 
import numpy as np 

df1=pd.read_csv('shared_articles.csv')
df2=pd.read_csv('users_interactions.csv')

In [ ]:
df1.head()

,timestamp,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang
eventType,,,,,,,,,,,,
CONTENT REMOVED,1459192779,-6451309518266745024,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en
CONTENT SHARED,1459193988,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en
CONTENT SHARED,1459194146,-7292285110016212249,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://cointelegraph.com/news/bitcoin-future-w...,Bitcoin Future: When GBPcoin of Branson Wins O...,The alarm clock wakes me at 8:00 with stream o...,en
CONTENT SHARED,1459194474,-6151852268067518688,3891637997717104548,-1457532940883382585,NaN,NaN,NaN,HTML,https://cloudplatform.googleblog.com/2016/03/G...,Google Data Center 360° Tour,We're excited to share the Google Data Center ...,en
CONTENT SHARED,1459194497,2448026894306402386,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,https://bitcoinmagazine.com/articles/ibm-wants...,"IBM Wants to ""Evolve the Internet"" With Blockc...",The Aite Group projects the blockchain market ...,en

In [ ]:
df2.head()

,timestamp,eventType,contentId,personId,sessionId,userAgent,userRegion,userCountry
0,1465413032,VIEW,-3499919498720038879,-8845298781299428018,1264196770339959068,NaN,NaN,NaN
1,1465412560,VIEW,8890720798209849691,-1032019229384696495,3621737643587579081,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,NY,US
2,1465416190,VIEW,310515487419366995,-1130272294246983140,2631864456530402479,NaN,NaN,NaN
3,1465413895,FOLLOW,310515487419366995,344280948527967603,-3167637573980064150,NaN,NaN,NaN
4,1465412290,VIEW,-7820640624231356730,-445337111692715325,5611481178424124714,NaN,NaN,NaN

In [ ]:
df1 = df1[df1['eventType'] == 'CONTENT SHARED']
df1.head()

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang
1,1459193988,CONTENT SHARED,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en
2,1459194146,CONTENT SHARED,-7292285110016212249,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://cointelegraph.com/news/bitcoin-future-w...,Bitcoin Future: When GBPcoin of Branson Wins O...,The alarm clock wakes me at 8:00 with stream o...,en
3,1459194474,CONTENT SHARED,-6151852268067518688,3891637997717104548,-1457532940883382585,NaN,NaN,NaN,HTML,https://cloudplatform.googleblog.com/2016/03/G...,Google Data Center 360° Tour,We're excited to share the Google Data Center ...,en
4,1459194497,CONTENT SHARED,2448026894306402386,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,https://bitcoinmagazine.com/articles/ibm-wants...,"IBM Wants to ""Evolve the Internet"" With Blockc...",The Aite Group projects the blockchain market ...,en
5,1459194522,CONTENT SHARED,-2826566343807132236,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.coindesk.com/ieee-blockchain-oxford...,IEEE to Talk Blockchain at Cloud Computing Oxf...,One of the largest and oldest organizations fo...,en

In [ ]:
df1.shape

(3122, 12)

In [ ]:
def find_total_events(df1_row):
  totalView = df2[(df2['contentId'] == df1_row['contentId']) & df2['eventType'] == 'VIEW'].shape[0]
  totalLike = df2[(df2['contentId'] == df1_row['contentId']) & df2['eventType'] == 'LIKE'].shape[0]
  totalBookmark = df2[(df2['contentId'] == df1_row['contentId']) & df2['eventType'] == 'BOOKMARK'].shape[0]
  totalFollow = df2[(df2['contentId'] == df1_row['contentId']) & df2['eventType'] == 'FOLLOW'].shape[0]
  totalComments = df2[(df2['contentId'] == df1_row['contentId']) & df2['eventType'] == 'COMMENT CREATED'].shape[0]
  return totalView + totalLike + totalBookmark + totalFollow + totalComments
df1['total_events'] = df1.apply(total_events, axis=1)

In [ ]:
print(df1.head(50))

In [ ]:
df1=df1.sort_values(['total_events'],ascending=False)
df1.head()

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang,total_events
1,1459193988,CONTENT SHARED,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en,0
2093,1471477815,CONTENT SHARED,-5283009029345397378,4209517478660372522,5185454684179635438,NaN,NaN,NaN,HTML,https://cloud.google.com/appengine/docs/python...,Microservices Architecture on Google App Engine,"Though mostly isolated, services share some Ap...",en,0
2084,1471366025,CONTENT SHARED,-5850390492300666299,7645894863578715801,6107910099552275355,NaN,NaN,NaN,HTML,https://medium.com/@skamille/microservices-rea...,Microservices: Real Architectural Patterns,Microservices: Real Architectural Patterns A d...,en,0
2085,1471374783,CONTENT SHARED,-7165716941095296287,-1032019229384696495,880025729283447629,NaN,NaN,NaN,HTML,https://cloudplatform.googleblog.com/2016/08/w...,Advancing enterprise database workloads on Goo...,We are committed to making Google Cloud Platfo...,en,0
2086,1471431177,CONTENT SHARED,-5649504870272917833,2682799999279860984,-5776940196792685042,NaN,NaN,NaN,HTML,https://xorcatt.wordpress.com/2016/08/16/equat...,EquationGroup Tool Leak - ExtraBacon Demo,"Hi there, You may have heard that recently (15...",en,0

In [ ]:
df1 = df1.sort_values(['total_events'], ascending=[False])
df1.head()

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang,total_events
1,1459193988,CONTENT SHARED,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en,0
11,1459217624,CONTENT SHARED,1805789466376069146,-1032019229384696495,3042342415047984532,NaN,NaN,NaN,HTML,https://cloud.google.com/compute/docs/load-bal...,Setting Up HTTP(S) Load Balancing,HTTP(S) load balancing provides global load ba...,en,0
12,1459217735,CONTENT SHARED,-2081760549863309770,-1032019229384696495,3042342415047984532,NaN,NaN,NaN,HTML,https://cloud.google.com/compute/docs/load-bal...,Setting Up SSL proxy for Google Cloud Load Bal...,Alpha This is an Alpha release of Setting Up S...,en,0
3,1459194474,CONTENT SHARED,-6151852268067518688,3891637997717104548,-1457532940883382585,NaN,NaN,NaN,HTML,https://cloudplatform.googleblog.com/2016/03/G...,Google Data Center 360° Tour,We're excited to share the Google Data Center ...,en,0
4,1459194497,CONTENT SHARED,2448026894306402386,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,https://bitcoinmagazine.com/articles/ibm-wants...,"IBM Wants to ""Evolve the Internet"" With Blockc...",The Aite Group projects the blockchain market ...,en,0

In [ ]:
def convert_lowercase(x):
  if isinstance(x, str):
      return x.lower()
  else:
      return ''

df1["title"] = df1["title"].apply(convert_lowercase)
df1.head()

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang,total_events
1,1459193988,CONTENT SHARED,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"ethereum, a virtual currency, enables transact...",All of this work is still very early. The firs...,en,0
11,1459217624,CONTENT SHARED,1805789466376069146,-1032019229384696495,3042342415047984532,NaN,NaN,NaN,HTML,https://cloud.google.com/compute/docs/load-bal...,setting up http(s) load balancing,HTTP(S) load balancing provides global load ba...,en,0
12,1459217735,CONTENT SHARED,-2081760549863309770,-1032019229384696495,3042342415047984532,NaN,NaN,NaN,HTML,https://cloud.google.com/compute/docs/load-bal...,setting up ssl proxy for google cloud load bal...,Alpha This is an Alpha release of Setting Up S...,en,0
3,1459194474,CONTENT SHARED,-6151852268067518688,3891637997717104548,-1457532940883382585,NaN,NaN,NaN,HTML,https://cloudplatform.googleblog.com/2016/03/G...,google data center 360° tour,We're excited to share the Google Data Center ...,en,0
4,1459194497,CONTENT SHARED,2448026894306402386,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,https://bitcoinmagazine.com/articles/ibm-wants...,"ibm wants to ""evolve the internet"" with blockc...",The Aite Group projects the blockchain market ...,en,0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(df1['title'])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [ ]:
df1 = df1.reset_index()
indices = pd.Series(df1.index, index=df1['contentId'])

In [ ]:
def get_recommendations(contentId, cosine_sim):
    idx = indices[contentId]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    return df1['contentId'].iloc[movie_indices]

In [ ]:
get_recommendations(-4029704725707465084, cosine_sim2)

2418     174707786647990372
2449    5087084654882097891
137     8298709454703868984
262    -5679427141235752819
582     4118743389464105405
803     4625350031392752392
909      -39485845307123560
1623    5338677278233757627
2780    7088167897470452815
231    -8587352636561360574
Name: contentId, dtype: int64

In [ ]:
from google.colab import files

df1.to_csv('articles.csv')
files.download('articles.csv')